<div>

    <!-- Content top  section -->

    <!-- Network information -->
    <livewire:network-info wire:init="fetchInfo">

    <div class="flex justify-between flex-wrap px-5 sm:px-10 xl:px-0">

        <!-- Page title -->
        <h1 class="text-2xl md:text-3xl mb-5 md:mb-6 text-theme-text-primary sm:mr-5 font-bold">
            Blocks
        </h1>

        <div class="sm:flex items-center mb-6">
            <livewire:network-switcher>
        </div>
    </div>

    <!-- Main content -->
    <div class="main-content mb-5 py-5 md:py-10 md:rounded-lg">
        <div wire:init="fetchBlocks({{ $page }})" wire:poll.10s="fetchBlocks({{ $page }}, {{ true }})">

            <!-- Loading screen -->
            @if ($status === 'Loading')
                <div class="w-full">

                    <!-- Skeleton table loading effect -->
                    <livewire:table-skeleton
                        :limit="$limit"
                        :columnLabels="
                        [
                        'ID' => 'text-left',
                        'Height' => 'text-left',
                        'Timestamp' => 'text-left',
                        'Transactions' => 'text-right',
                        'Generated by' => 'text-right',
                        'Total forged' => 'text-right',
                        'Fees' => 'text-right'
                        ]
                        ">
                </div>
            @endif

            <div wire:loading.remove>

                <!-- Request failed -->
                @if ($status === 'Failure')

                    <livewire:error-screen :errorCode="$errorCode" :errorMessage="$errorMessage"/>

                @endif

                <!-- Successfull response -->

                @if ($status === 'Success')
                    <div class="">

                        <!-- Empty screen after request-->
                        @if (count($blocks) === 0)

                            <livewire:list-empty-screen title="Unfortunately" description="No results were found.">

                        @else

                            <!-- Results -->
                            <table class="table table-fixed">
                                <thead>
                                    <tr>
                                        <th scope="col" class="text-left">ID</th>
                                        <th scope="col" class="text-left">Height</th>
                                        <th scope="col" class="text-left">Timestamp</th>
                                        <th scope="col" class="text-right">Transactions</th>
                                        <th scope="col" class="text-right">Generated by</th>
                                        <th scope="col" class="text-right">Total forged</th>
                                        <th scope="col" class="text-right">Fees</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach ($blocks as $block)
                                        <livewire:block-list-item :data="$block" :key="$block['id']">
                                    @endforeach
                                </tbody>

                            </table>

                            <!-- Pager -->
                            <livewire:pagination :pageCount="$pageCount" :limit="$limit" :page="$page" contextLabel="blocks" :key="$page">
                        @endif
                    </div>
                @endif
            </div>

        </div>
    </div>
</div>
