<tr>
    <!-- Block template for table listing  -->

    <td scope="row" data-label="ID">
        <div class="truncate"><a class="link" href="{{ $block['path'] }}" title="{{ $block['id']}}">{{ $block['id'] }}</a></div>
    </td>

    <td scope="row" data-label="Height">
        <div class="truncate">{{ $block['height'] }}</div>
    </td>

    <td scope="row" data-label="Timestamp">
        <div class="truncate">{{ $block['timestamp'] }}</div>
    </td>

    <td scope="row" data-label="Transactions" class="text-right">
        <div class="truncate">{{ $block['transactions'] }}</div>
    </td>

    <td scope="row" data-label="Generated by" class="text-right">
        <div class="truncate">
            <a class="link"
               href="{{ $block['generatorPath'] }}"
               title="{{ $block['generatorAddress'] }}">
                {{ $block['generatorUsername'] }}
            </a>
        </div>
    </td>

    <td scope="row" data-label="Total forged" class="text-right">
        <div class="truncate">
            {{ $block['forgedTotal'] }}
            <span>Ѧ</span>
        </div>
    </td>
    <td scope="row" data-label="Fees" class="text-right">
        <div class="truncate">
            {{ $block['fee'] }}
            <span>Ѧ</span>
        </div>
    </td>

</tr>
