<div>
    <!-- Network information -->
    <livewire:network-info wire:init="fetchInfo">

    <!-- Page title -->
    <div class="flex justify-between flex-wrap px-5 sm:px-10 xl:px-0">
        <h1 class="text-2xl md:text-3xl mb-5 md:mb-6 text-theme-text-primary sm:mr-5 font-bold">
            Block details
        </h1>
    </div>
    <!-- Content top section  (Block info) -->
    <section class="mb-5 bg-theme-feature-background xl:rounded-lg flex-col items-center px-2 sm:px-10 py-8 text-white">
        <div><h2 class="text-lg font-bold">Block ID:</h2></div>
        <div class="truncate text-xl">{{ $blockId }}</div>
    </section>

    <!-- Main content -->
    <div class="main-content mb-5 py-5 md:py-10 md:rounded-lg" wire:init="fetchBlock">

        <!-- Request failed -->
        @if ($status === 'Failure')

            <livewire:error-screen :errorCode="$errorCode" :errorMessage="$errorMessage"/>

        @else
            <!-- Main content -->
            <!-- Showing skeleton sections on value -->
            <div class="px-5 sm:px-10">

                <div class="detail-row flex-row">
                    <div class="mr-4"> Transactions </div>
                    <div wire:loading class="w-32"><div class="skeleton"></div></div>
                    <div wire:loading.remove>{{ $block['transactions'] }}</div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Confirmations </div>
                    <div wire:loading class="w-32"><div class="skeleton"></div></div>
                    <div wire:loading.remove>{{ $block['confirmations'] }}</div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Height </div>
                    <div wire:loading class="w-40"><div class="skeleton"></div></div>
                    <div wire:loading.remove>{{ $block['height'] }}</div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Reward </div>
                    <div wire:loading class="w-12"><div class="skeleton"></div></div>
                    <div wire:loading.remove> ${{ $block['reward'] }} Ѧ </div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Fees </div>
                    <div wire:loading class="w-16"><div class="skeleton"></div></div>
                    <div wire:loading.remove> {{ $block['fees'] }} Ѧ </div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Total forged </div>
                    <div wire:loading class="w-16"><div class="skeleton"></div></div>
                    <div wire:loading.remove> {{ $block['forgedTotal'] }} Ѧ </div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Processed amount </div>
                    <div wire:loading class="w-16"><div class="skeleton"></div></div>
                    <div wire:loading.remove> {{ $block['processedAmount'] }} Ѧ </div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Timestamp </div>
                    <div wire:loading class="w-40"><div class="skeleton"></div></div>
                    <div wire:loading.remove>{{ $block['timestamp'] }}</div>
                </div>

                <div class="detail-row">
                    <div class="mr-4"> Generated by </div>
                    <div wire:loading class="w-16"><div class="skeleton"></div></div>
                    <a class="link" wire:loading.remove href="{{ $block['generatorPath'] }}" title="{{ $block['generatorAddress']}}">{{ $block['generatorUsername'] }}</a>
                </div>
            </div>
        @endif
    </div>
</div>
